export const ON_CHANGE_CUSTOMER = 'ON_CHANGE_CUSTOMER';
export const ON_QUANTITY_CHANGED = 'ON_QUANTITY_CHANGED';
export const ADD_TO_CART = 'ADD_TO_CART';
export const RECEIVED_CUSTOMERS = 'RECEIVED_CUSTOMERS';
export const RECEIVED_PLANS = 'RECEIVED_PLANS';
export const RECEIVED_DISCOUNTS = 'RECEIVED_DISCOUNTS';